modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="broken_world_extra"
version="1.0.0"
displayName="broken world extra"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="jackh, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.broken_world_extra]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration